### ISSUE TITLE
^ and _

### ISSUE THREAD

**Issue by nosami** [hifi/monodevelop-justenoughvi#12]
To move to the first non-whitespace char. Can also be used in motions

**Comment by hifi** [comment]
Commit b3c3c45149f7cb3f5ced7dd59413a238a8c5e375 adds ^ and bd0b4729a4016f535f1b7b8013d3e61f6134d3cc  _.  Motions not yet implemented.

**Comment by hifi** [comment]
Commit 21021c2e398ec563e518c0c6249d64c3f21c5845 turns the keys into generic motions.
