### ISSUE TITLE
Let all Control combinations pass even in normal mode?

### ISSUE THREAD

**Issue by hifi** [hifi/monodevelop-justenoughvi#17]
Have normal bindings available for all Vi functions and a default keymap. Only regular characters would be captured and the escape sequence.

**Comment by nosami** [comment]
I just remapped Ctrl-d and Ctrl-u in the monodevelop settings. But what about Ctrl-v for block select? That will need special handling.

**Comment by hifi** [comment]
Currently, the idea is to capture all possible combinations that we want to support. Will open a new issue if it turns out to be a bad idea.
