### ISSUE TITLE
Dependency could not be resolved.

### ISSUE THREAD

**Issue by MirzaSikander** [hifi/monodevelop-justenoughvi#31]
On the latest Xamarin studio 6.0.1, I am getting the following error: 
![screen shot 2016-06-24 at 12 54 45 pm](https://cloud.githubusercontent.com/assets/2823474/16349017/f35fdb7c-3a0a-11e6-892c-f6bbfc4ca0e4.png)

**Comment by hifi** [comment]
Can't reproduce this with MD 6.0.1 built from git. Is that 6.0.1 or 6.1?

**Comment by hifi** [comment]
I got information that there was a bug in XS 6.0.1 and it should have been resolved now:

https://releases.xamarin.com/xamarin-studio-stable-hotfix-for-incompatible-xs-addins/

Please reopen this issue if you encounter this again. Thanks!
