### ISSUE TITLE
gg should go to the first line of file

### ISSUE THREAD

**Issue by thawatchai** [hifi/monodevelop-justenoughvi#32]
Could you implement `gg` to go to the first line of file instead of the last line (currently the same behavior as `G`)? This will make `gg` work the same way as Vim.

BTW, thank you very much for this excellent plugin. When I have to use Xamarin Studio 6 that is shipped without `vi` feature, this plugin saves me from adapting arrow keys for file navigation, which I've never done for years.

Also, I try to fork and help implementing this requested feature, but it seems that I need a linux box to do that, which I don't have now. 😩 

Thawatchai

**Comment by hifi** [comment]
There's no requirement of Linux to work on this project. I've tried XS on Windows as well and I think @nosami was on OS X the whole time he worked on this.

It should be easy to make the change. You can go to the first line with `1G` for now.

**Comment by thawatchai** [comment]
Oh, cool! I'm using a Mac. I was trying to open the solution with Xamarin Studio, and it shows something like `Could not load project 'JustEnoughVi.csproj' with unknown item type [....`

I just realize that I need MonoDevelop development assemblies and Add-in Maker (available in add-in catalogue).

**Comment by hifi** [comment]
Ah, yes, that is true. Without Add-in Maker it can't be loaded at all.

If you find anything interesting to implement, feel free to send a pull request. Thanks!

**Comment by thawatchai** [comment]
Thanks, I'll try. 😄

**Comment by nosami** [comment]
@thawatchai You need Add-in Maker but you shouldn't need any development assemblies. Add-in Maker references the installed Xamarin Studio assemblies invisibly.

**Comment by thawatchai** [comment]
Thanks @nosami
