### ISSUE TITLE
How do you turn it on with Xamarin Studio 6.0.1

### ISSUE THREAD

**Issue by biozal** [hifi/monodevelop-justenoughvi#38]
installed plugin - but not sure how to even turn on?  it's not working in Xamarin Studio 6.0.1 (build 9).  Any documentation on what needs to be done to make it work?

**Comment by hifi** [comment]
Restarting MD/XS will activate it. Unbinding Vi keys from XS enables them within the plugin if they are supported.

**Comment by NamXH** [comment]
You probably want to write a few lines about how to install in the readme. Thanks for the plugin 👍

**Comment by thawatchai** [comment]
This add-in works on Xamarin Studio 6.0.2 as well. If anyone upgrades it to 0.11, and it doesn't work. You should remove it, restart XS, then install it again. It will work after restarting XS.

**Comment by lukedupin** [comment]
I agree, just a few lines on installing the plugin would have been great.  Plugin works really well, thanks a bunch for your work, major improvement over default key bindings.
