### ISSUE TITLE
Switch focus to column/window with Ctrl+W

### ISSUE THREAD

**Issue by mixedCase** [hifi/monodevelop-justenoughvi#41]
Feature request

In Vim you can switch to a different window by using Ctrl+W and the direction key the window is located in with respect to the currently focused one. Ctrl+W H and Ctrl+W L would be an amazing productivity boost, as little change as it seems to be.

**Comment by hifi** [comment]
Should be doable, will look into it.

**Comment by nosami** [comment]
Please could you add `Ctrl+W W` too? 
I use this more often as it's easier to type. It cycles between open editor panes.

**Comment by hifi** [comment]
Not sure if I did it right but just pushed the aliases.
