### ISSUE TITLE
^d doesn't work

### ISSUE THREAD

**Issue by quanticPI** [hifi/monodevelop-justenoughvi#53]
Currently ^d does not go page up but deletes a character.

**Comment by hifi** [comment]
You need to unbind the key combination in MonoDevelop/Xamarin Studio for this add-in to capture it.

The control key mapping in the add-in that includes ^D is here and should work:
https://github.com/hifi/monodevelop-justenoughvi/blob/master/JustEnoughVi/ViMode.cs#L157

**Comment by quanticPI** [comment]
I suspected there was something wrong with my configuration...
Thank you.

**Comment by hifi** [comment]
We still don't have any README or documentation so it's understandable people don't know how it works. Good you got it going!
